name: neovim

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly
      - name: Run unit tests
        run: |
          nvim --version
          nvim -u NONE -N --noplugin -c "set rtp+=." -c "call qfprediction#run_tests()" -c "qa!"
          if test -f test.log; then exit 1; fi

